#%RAML 1.0 ResourceType
post?:
    description: creates a <<ObjectNamePOST>> record 
    body:
        application/json:
          type: <<ObjectTypeNamePOST>>
    responses:
        200:
          description: <<SuccessResponseTypeNamePOST>>
          body: 
              application/json:
                type: <<SuccessResponseTypeNamePOST>>
        400:
          description: Bad request
          body: 
            application/json:
              type: <<ErrorResponseTypeName>>
        404:
          description: Resource <<resourcePath>> not found
          body: 
            application/json:
              type: <<ErrorResponseTypeName>>
              
        401:
          description: Unauthorized 
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
              
        500:  
          description: Internal server 
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
                
        405:
          description: Method not allowed
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>  
put?:
    description: Update a <<ObjectNamePUT>> record 
    body:
        application/json:
          type: <<ObjectTypeNamePUT>>
    responses:
        200:
          description: <<SuccessResponseTypeNamePUT>>
          body: 
              application/json:
                type: <<SuccessResponseTypeNamePUT>> 
        400:
          description: Bad request
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
        404:
          description: Resource <<resourcePath>> not found
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
        401:
          description: Unauthorized 
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
        500:  
          description: Internal server 
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
        405:
          description: Method not allowed
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
patch?:
    description: Patch a <<ObjectNamePATCH>> record 
    body:
        application/json:
          type: <<ObjectTypeNamePATCH>>
    responses:
        200:
          description: <<SuccessResponseTypeNamePATCH>>
          body: 
              application/json:
                type: <<SuccessResponseTypeNamePATCH>> 
        400:
          description: Bad request
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
        404:
          description: Resource <<resourcePath>> not found
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
        401:
          description: Unauthorized 
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
        500:  
          description: Internal server 
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
        405:
          description: Method not allowed
          body: 
            application/json:
              type:  <<ErrorResponseTypeName>>
get?:
  description: Get a <<SuccessResponseTypeName>> record 
  responses:
      200:
        description: <<SuccessResponseTypeName>>
        body: 
            application/json:
              type: <<SuccessResponseTypeName>>
      500:  
        description: Internal server 
        body: 
          application/json:
            type:  <<ErrorResponseTypeName>>
      404:
        description: Resource <<resourcePath>> not found
        body: 
          application/json:
            type:  <<ErrorResponseTypeName>>
      401:
        description: Unauthorized 
        body:
          application/json:
            type:  <<ErrorResponseTypeName>>
      405:
        description: Method not allowed
        body: 
          application/json:
            type:  <<ErrorResponseTypeName>>
