#%RAML 1.0 DataType
type: object
description: 'Defines structure of create action Item request'
#examples: !include ../examples/ActionItem.raml
properties: 
  occuranceDate:
    type: datetime
    required: true
  dateClosed:
    type: datetime
    required: false
  followUpDate:
    type: datetime
    required: false
  comments:
    type: string
    minLength: 1
    maxLength: 2000
    required: false
  studyIssueTypeName:
    type: !include StudyIssueType.raml
    required: true
  notes:
    type: string
    minLength: 1
    maxLength: 2000
    required: true
  studyIssueStatusName:
    type: string
    required: true
    minLength: 1
    maxLength: 50
    enum:
      - Closed
      - Opened
      - Resolved
  protocolId:
    type: integer
    required: true
  protocolSiteId:
    type: integer
    required: true
  entityId:
    type: integer
    required: true
    enum:
      - 0
  recordStatus:
    type: integer
    required: true
    enum:
      - 0
  recordLocked:
    type: integer
    required: false
    enum:
      - 0
      - 1
  allowOMVRUpdates:
    type: integer
    required: true
    enum:
      - 1
  dateCreated:
    type: datetime
    required: true
  dateStart:
    type: datetime
    required: true
  lastUser:
    type: integer
    required: true
  

  

 