#%RAML 1.0 DataType
type: object
description: 'Defines structure of create Site Visit Participant request'
#examples: !include ../examples/SiteVisitParticipant.raml
properties: 
  contactId:
    type: integer
    required: true
  protocolSiteId:
    type: integer
    required: true
  role:
    type: string
    maxLength: 80
    required: true
    enum:
      - Sub-Investigator
      - Study Coordinator
      - Data Manager
      - Pharmacist
  emailAddress:
    type: string
    maxLength: 80
    required: false
  emailType:
    type: string
    maxLength: 20
    required: false
    enum:
      - Primary
  dateCreated:
    type: datetime
    required: true
  dateStart:
    type: datetime
    required: true
  sharedEmailAddress:
    type: integer
    required: false
    enum:
      - 0
  isPrimary:
    type: integer
    required: false
    enum:
      - 0
  entityId:
    type: integer
    required: true
    enum:
      - 0
  recordStatus:
    type: integer
    required: true
    enum:
      - 0
  fromAsco:
    type: integer
    required: false
    enum:
      - 0
  lastUser:
    type: integer
    required: true

  
