#%RAML 1.0 DataType
type: object
displayName: Error Response Type
description: 'This type defines structure of error response'
#examples: !include ../examples/ErrorResponse.raml
properties: 
  message: 
    type: string
    description: 'Short description of error message'
  details?: 
    type: string
    description: 'Detailed description of error message'
