#%RAML 1.0 DataType
    type: string
    minLength: 1
    maxLength: 50
    enum:
      - ISSC Site File Issue
      - ISSC MV Doc Issue
      - Investigator Site Binder
      - Site Staff Training
      - Source Documentation
      - Study Product 
      - CA/EC/IRB
      - Central/Local Lab
      - Event Reporting/Safety
      - Recruitment & Enrollment
      - Facilities & Equipment
      - Systems
      - Study Supplies
      - Data Entry/Query Resolution
      - Other


