#%RAML 1.0 DataType
type: object
description: 'Defines structure of update Protocol Deviation request'
#examples: !include ../examples/ProtocolDeviation.raml
properties: 
  pdDeviationId:
    type: integer
    required: true
  recordLocked:
    type: integer
    required: true
    enum:
      - 0
      - 1
  protocolSiteId:
    type: integer
    required: true
  patientNumber:
    type: string
    maxLength: 50 
    required: true
  noSubjectAssociated:
    type: integer
    required: true
    enum:
      - 0
      - 1
  protocolId:
    type: integer
    required: true 
  dateReported:
    type: datetime
    required: true
  dateOccurred:
    type: datetime
    required: true
  pdCategoryName:
    type: !include PDCategoryName.raml
    required: true
  description:
    type: string
    required: true
    maxLength: 1024
  subjectWithdrawn:
    type: integer
    required: true
    enum:
      - 0
      - 1
  irbecReportReq:
    type: integer
    required: true
    enum:
      - 0
      - 1
  actualIrbecReportDate:
    type: datetime
    required: false
  expectedIrbecReportDate:
    type: datetime
    required: false
  dateSponsorNotified:
    type: datetime
    required: false
  dateSponsorAcknowledged:
    type: datetime
    required: false
  status:
    type: string
    maxLength: 64
    required: true
    enum:
      - Ready for CTM Review
      - Ready for Sponsor Review
      - More Info Required
      - Closed
      - Cancelled
  followUpRequired:
    type: integer
    required: true
    enum:
      - 0
      - 1
  pdFollowUpActionName:
    type: string
    maxLength: 50
    required: false
    enum:
      - Get more information
      - Send for review
      - None
  followUpCorrective:
    type: string
    maxLength: 1024
    required: false
  followUpPreventative:
    type: string
    maxLength: 1024
    required: false
  majorMinor:
    type: string
    maxLength: 64
    required: true
    enum:
      - Minor
      - Major
  lastUser:
    type: integer
    required: true
  
  

  
    


  

 