#%RAML 1.0 DataType
type: object
description: 'Defines structure of update action Item request'
#examples: !include ../examples/SiteVisit.raml
properties: 
  monitoringVisitID:
    type: integer
    required: true
  monitoringMethod:
    type: string
    required: true
    minLength: 1
    maxLength: 30
    enum:
      - Phone
      - Site
      - COVID19 rDV
      - COVID19 SMC
      - COVID19 rSDM
  monitoringVisitType:
    type: string
    required: true
    minLength: 1
    maxLength: 30
    enum:
      - Site Evaluation Visit
      - Site Initiation Visit
      - Interim Monitoring Visit
      - Close Out Visit
  actualVisitDate:
    type: datetime
    required: false
  visitEndDate:
    type: datetime
    required: false
  visitStatus:
    type: string
    required: true
    minLength: 0
    maxLength: 30
    enum:
      - Planned
      - Confirmed
      - Actual
      - Waived
      - Cancelled
      - ""
  visitDays:
    type: integer
    required: true
  plannedVisitDate:
    type: datetime
    required: false
  protocolSiteID:
    type: integer
    required: true
  contactID:
    type: integer
    required: true
  isWaived:
    type: integer
    required: false
    enum:
      - 0
      - 1
  documentType:
    type: string
    required: true
    minLength: 1
    maxLength: 100
    enum:
      - SEV Confirmation Letter,SEV Follow-up Letter
      - SIV Confirmation Letter,SIV Follow-up Letter
      - IMV Confirmation Letter,IMV Follow-up Letter
      - COV Confirmation Letter,COV Follow-up Letter
  confirmedDate:
    type: datetime
    required: false
  followUpLetterDate:
    type: datetime
    required: false
  documentVersion:
    type: integer
    required: true
  primaryVisitContact:
    type: integer
    required: true
    enum:
      - 1
  lastUser:
    type: integer
    required: true
  
  