#%RAML 1.0 NamedExample
value: {
   "message": "Access is denied due to invalid credentials",
   "details": " javax.script.ScriptException: org.springframework.security.authentication.BadCredentialsException: api.csmondemand.com Error Code: 401 Error Message :Invalid token"
}
