#%RAML 1.0 NamedExample
value: {
"pdDeviationId": 3099,
"recordLocked": 0,
"protocolSiteId": 2731,
"patientNumber": "00014-0021",
"noSubjectAssociated": 0,
"protocolId": 834,
"dateReported": 2016-02-28T16:41:41.090Z,
"dateOccurred" : 2016-02-28T16:41:41.090Z,
"pdCategoryName": "Informed Consent Criteria",
"causality": "N/A",
"description": " C19 visit occurred -3 days out of window",
"subjectWithdrawn": 0,
"irbecReportReq": 0,
"actualIrbecReportDate": 2016-02-28T16:41:41.090Z,
"expectedIrbecReportDate": 2016-02-28T16:41:41.090Z,
"dateSponsorNotified": 2016-02-28T16:41:41.090Z,
"dateSponsorAcknowledged": 2016-02-28T16:41:41.090Z,
"status" : "More Info Required",
"followUpRequired" :0,
"pdFollowUpActionName": "Get more information",
"followUpCorrective": "",
"followUpPreventative": "",
"majorMinor": "Major",
"dateCreated": 2016-02-28T16:41:41.090Z,
"dateStart": 2016-02-28T16:41:41.090Z,
"sponsorAcknowledged": 0,
"piNotified": 0,
"entityId" : 0,
"recordStatus" :0,
"lastUser": 4

}