#%RAML 1.0 NamedExample
value: {
"monitoringVisitID": 22682,
"monitoringMethod": "Site",
"monitoringVisitType": "Site Evaluation Visit",
"actualVisitDate": 2016-02-28T16:41:41.090Z,
"visitEndDate": 2016-02-28T16:41:41.090Z,
"visitStatus": "Confirmed",
"visitDays": 15,
"plannedVisitDate": 2016-02-28T16:41:41.090Z,
"protocolSiteID": 27926,
"contactID": 22924,
"isWaived": 0,
"documentType" : "SEV Confirmation Letter,SEV Follow-up Letter",
"confirmedDate": 2016-02-28T16:41:41.090Z,
"documentVersion" :1,
"dateCreated": 2016-02-28T16:41:41.090Z,
"dateStart": 2016-02-28T16:41:41.090Z,
"primaryVisitContact": 1,
"docNeedsReview": 0,
"mustBeTracked" : 0,
"isTemplate" : 0,
"rfEnrollment" : 0,
"rfStudy" : 0,
"rfIpShipment": 0,
"rfAudit" : 0,
"rfIrbEcSubmittal" : 0,
"rtBeforeSend" : 0,
"rtAfterReceived" : 0,
"rtFinal" : 0,
"entityId" : 0,
"recordStatus" : 0,
"documentSkipped" : 0,
"mvrDocStatus" : 0,
"lastUser": 4
}