#%RAML 1.0 NamedExample
value:
  {

"lastUser": 9,
"entityId": 0,
"isCheckedOut": 0,
"isInternalViewOnly": 0,
"contentSize": 0,
"signStatus": 1,
"signAction": "FinalApprovalSignature",
"relatedAttachmentRev": 0,
"isLocked": 0,
"version": 0,
"recordStatus": 0,
"relatedTypeId": 1,
"locationDetailId": 0,
"retries": 0,
"versionNumber": 0,
"status": "success",
"migrationError": "Null",
"monitoringVisitId": 0,
"migrationDate": "2016-02-28T16:41:41.090Z",
"attachmentName": "Site Visit Document",
"author": 0,
"dateSigned": "2016-02-28T16:41:41.090Z",
"dateSignedUser": "2016-02-28T16:41:41.090Z",
"relatedAttachment": 49,
"objectType": "Site Visit Document",
"revisionNumber": 0,
"wsUrl": "https://tmftransform01.testing.mywingspan.com/wingspan-tmf/tmf/documentslist#detail/?state=&id=1000551600000000008E8DBF",
"siteVisitType": "IMV"
}