#%RAML 1.0 NamedExample
value: {
"contactId" : 3,
"protocolSiteId" : 23,
"emailAddress" : "contact@test.com",
"emailType" : "Primary",
"role" : "Sub-Investigator",
"dateCreated" : "2016-02-28T16:41:41.090Z",
"dateStart" : "2016-02-28T16:41:41.090Z",
"sharedEmailAddress" : 0,
"isPrimary" : 0,
"entityId" : 0,
"recordStatus" : 0,
"fromAsco" : 0,
"lastUser" : 4

}